/*
 * July 25, 2017
 * Stephan Motha
 * Hangman SUmmative
 * make a GUI that allows a user to play a game of hangman. 
 * have requirements like arrays, sorting writing to a file etc
 */
package hangman.summative;


import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;

/**
 *
 * @author Stephan
 */
public class WinScreen extends javax.swing.JFrame {

    /**
     * Creates new form WinOrLose
     */
    double time;
    //this function takes in the time from the main screen as a constructor
    public WinScreen(double x) throws IOException {
        this.time = x;
        initComponents();
        
        lblExclamation.setText("Your time was "+(int)time/1000+" seconds");//sets the statement of their time
        read();//calls read function
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWinOrLose = new javax.swing.JLabel();
        btnQuit = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        btnEnterName = new javax.swing.JButton();
        lblEnterYourName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaScores = new javax.swing.JTextArea();
        lblExclamation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblWinOrLose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblWinOrLose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWinOrLose.setText("You Win!");

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnEnterName.setText("Enter");
        btnEnterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterNameActionPerformed(evt);
            }
        });

        lblEnterYourName.setText("Enter Your Name");

        txtAreaScores.setColumns(20);
        txtAreaScores.setRows(5);
        jScrollPane1.setViewportView(txtAreaScores);

        lblExclamation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("See below for the names and times (seconds) of the people who played before you!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblWinOrLose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblExclamation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnterYourName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWinOrLose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExclamation, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterYourName)
                    .addComponent(btnEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(btnQuit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //this class will store the info of the user (name and score
    class Users{ 
        String name;
        int score;
        public Users(String x, int y){//function that accepts name and score. will store it in  name and score variables
            this.name = x;
            this.score = y;
        }
        
    }
    ArrayList<Users> users = new ArrayList();
    //this function will exit the program when they click exit
    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_btnQuitActionPerformed
    
    //this function will read the info that is in the scores.txt file
    private void read() throws IOException {
        BufferedReader file = new BufferedReader(new FileReader("scores.txt"));//names the file
        String line;
        //the following will read through the info in the file
        while ((line = file.readLine()) != null)
        {
            System.out.println(line);
            String[] tokens = line.split(" ");
            String name = tokens[0];
            int score = Integer.parseInt(tokens[1]);
            users.add(new Users(tokens[0], Integer.parseInt(tokens[1])));//creates new object in users class
            
        }

    }
    //this function will write to the scores.txt file using the users class
    private void write() throws IOException{ 
        String output = "";
        FileWriter fw = new FileWriter("scores.txt"); 
        PrintWriter pw = new PrintWriter(fw);
        output = ""; 
        for (int i = 0; i<users.size(); i++){
            output += (users.get(i).name +" "+users.get(i).score+"\n");//iterates through each object in Users class
        }
        this.txtAreaScores.setText(output);//output whatever scores are already saved
        pw.printf(output); 
        pw.close();
        fw.close();
    }
    //this function will occur when the enter button is clicked
    //it will enter the user info as an instance of the class Users
    private void btnEnterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterNameActionPerformed

        String name = this.txtName.getText();
        users.add(new Users(name,(int)(time/1000)));//instance of Users class
        
        try {
            write();//
        } catch (IOException io) {
            io.printStackTrace();
        }
    }//GEN-LAST:event_btnEnterNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterName;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterYourName;
    private javax.swing.JLabel lblExclamation;
    private javax.swing.JLabel lblWinOrLose;
    private javax.swing.JTextArea txtAreaScores;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
